{% set name = "maup" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8e45c71af8263ef7039fb747bfe9706cf4e6b1fc3393d21284416b426974cb1

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - pandas
    - shapely
    - geopandas
    - tqdm
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - maup

about:
  home: https://github.com/mggg/maup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The geospatial toolkit for redistricting data'

  description: |
    maup is the geospatial toolkit for redistricting data. The package streamlines
    the basic workflows that arise when working with census blocks and precinct
    shapefiles.
  doc_url: https://github.com/mggg/maup
  dev_url: https://github.com/mggg/maup

extra:
  recipe-maintainers:
    - maxhully
